### ISSUE TITLE
Add Twitter handle to basic info

### ISSUE THREAD

**Issue by filiptronicek** [yg/git-stalk#4]
As of somewhere at the end of May, GitHub has added a feature to tag your Twitter handle to your profile. I think it would be a good idea to add it to the CLI as well
![example picture](https://user-images.githubusercontent.com/29888641/83401686-a5b33b80-a405-11ea-8e27-2c779846fe99.png)

**Comment by yg** [comment]
Thanks for the suggestion @filiptronicek! Just shipped :rocket:
